/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class AppTest {
    // @Test fun appHasAGreeting() {
    //     val classUnderTest = App()
    //     assertNotNull(classUnderTest.greeting, "app should have a greeting")
    // }

    @Test fun `12 умножить на 2 в строке`() {
        val app = App()
        assertEquals(app.returnTwoTimesTwelveInString(), "24 ")
    }
}
